[package]
name = "hpke"
version = "0.1.0"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"

[dependencies]
aead = "0.2"
aes-gcm = "0.5"
byteorder = "1.3"
chacha20poly1305 = "0.4"
digest = "0.8"
hkdf = "0.8"
rand = "0.7"
sha2 = "0.8"
x25519-dalek = "0.6"

[dev-dependencies]
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
