[package]
name = "hpke"
repository = "https://github.com/rozbb/rust-hpke"
documentation = "https://docs.rs/rust-hpke"
description = "An implementation of the HPKE hybrid encryption standard in pure Rust"
readme = "README.md"
version = "0.1.3"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["cryptography", "key-exchange", "encryption", "aead"]
categories = ["cryptography", "no-std"]

[features]
default = ["std"]
std = []

[dependencies]
aead = "0.2"
aes-gcm = "0.5"
byteorder = "1.3"
chacha20poly1305 = "0.4"
digest = "0.8"
hkdf = "0.8"
rand = "0.7"
p256 = {version = "0.2", features = ["arithmetic"]}
sha2 = "0.8"
subtle = "2.2"
x25519-dalek = "0.6"
zeroize = {version = "1.1", features = ["zeroize_derive"]}

[dev-dependencies]
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
