name: Security Audit
on:
  pull_request_target:
    paths:
      - '**/Cargo.toml'
  push:
    paths:
      - '**/Cargo.toml'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
